CREATE PROC [STA].[SP_LOAN_AR] AS

-- BRCD_ID ALANININ STAGE TABLOLARINDAN UPDATE EDILMESINI SAÐLAR. 
-- 2015.10.16 GOKCEUL

IF EXISTS (SELECT * FROM stagedb.sys.objects WHERE NAME='LOAN_AR' AND type in (N'U') AND SCHEMA_ID = 7)
DROP TABLE stagedb.STA.LOAN_AR;


CREATE  TABLE stagedb.[STA].[LOAN_AR] WITH (DISTRIBUTION = HASH(HESAP))
as
SELECT 
t3.*
FROM (SELECT
t1.SUBE,
t1.HESAP,
t1.EK,
t1.TARIH,
t2.CR_USG_DT AS KULLANIM_TARIHI,
t2.CCY_CODE AS DVZ_KODU,
t2.IDV_CORP_IND AS TICARI_FLAG,
FC_IDNXD_LOAN_CODE AS DEK, 
t2.OVNGT_CODE AS OD_CODE,
t2.CMPN_CODE,
ROW_NUMBER() OVER (PARTITION BY t1.SUBE,t1.HESAP,t1.EK ORDER BY t1.TARIH desc) AS SIRA_NO,
t2.CR_VAL_DT AS HESAPLAMA_TARIHI,
t2.CR_AC_OPN_OPN_DT AS KREDI_ACILIS_TARIHI,
t2.CR_AC_OPN_USR_CODE AS KULLANDIRIM_KULLANICI,
t2.PD_CODE AS URUN_KODU,
t2.CR_AMT AS KULLANDIRIM_TUTAR,
t2.WF_ACTN_NBR AS WF_ACTN_NBR,
t2.CR_OPN_REFR_NBR AS LOG_NBR,
t2.CR_OPN_BR_CODE AS LOG_BR_CODE,
convert(int,convert(varchar(10),t2.CR_AC_OPN_OPN_DT, 112)) AS LOG_DT_NBR
FROM
( SELECT 
CR_AC_BR_CODE AS SUBE ,
CR_AC_NBR AS HESAP,
CR_AC_SUFX_NBR AS EK,
MAX(CASE WHEN PD_CODE <>'URETKRD' AND CR_AC_OPN_OPN_DT IS NULL THEN CR_USG_DT 
         WHEN PD_CODE <>'URETKRD' AND CR_AC_OPN_OPN_DT IS NOT NULL THEN  CR_AC_OPN_OPN_DT 
		 WHEN PD_CODE ='URETKRD' THEN CR_VAL_DT END) AS TARIH
FROM  dbo.LOAN_AR
WHERE 
CR_TP IN ('TK','CM','CA','CR','IC')  
AND 
PD_CODE IN ('KONTKRD','TASKRED','IHTKRED','KRDLMEV','DGRGMKR','MALKKRD','YATKRED','DGRNKRD','DGRTKST','IHRKRED','YDISKRD','ITHKRED','EXIMKRD','ISKONTO','ISKONTS','ISLTKRD','KAMUKRD','CMKREDI','MADKRED','DGRYTKR','ISLMKRD','TRAKKRD','URETKRD','YATKRED','HSNKRED','IHTKTIC','KONTISY','TASKTIC')  
GROUP BY
CR_AC_BR_CODE,
CR_AC_NBR,
CR_AC_SUFX_NBR
)t1 
LEFT JOIN dbo.LOAN_AR t2 ON t1.SUBE=CR_AC_BR_CODE AND t1.HESAP=t2.CR_AC_NBR  AND t1.EK=CR_AC_SUFX_NBR 
AND t1.TARIH=(CASE WHEN PD_CODE <>'URETKRD' AND CR_AC_OPN_OPN_DT IS NULL THEN CR_USG_DT 
         WHEN PD_CODE <>'URETKRD' AND CR_AC_OPN_OPN_DT IS NOT NULL THEN  CR_AC_OPN_OPN_DT 
		 WHEN PD_CODE ='URETKRD' THEN CR_VAL_DT END) 
AND t2.CR_TP in ('TK','CM','CA','CR','IC') AND t2.PD_CODE IN ('KONTKRD','TASKRED','IHTKRED','KRDLMEV','DGRGMKR','MALKKRD','YATKRED','DGRNKRD','DGRTKST','IHRKRED','YDISKRD','ITHKRED','EXIMKRD','ISKONTO','ISKONTS','ISLTKRD','KAMUKRD','CMKREDI','MADKRED','DGRYTKR','ISLMKRD','TRAKKRD','URETKRD','YATKRED','HSNKRED','IHTKTIC','KONTISY','TASKTIC')  
) t3																																												                
WHERE t3.SIRA_NO=1   ;
 





